name: Code Quality & Metrics

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for better analysis

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Code complexity analysis
      run: |
        echo "=== Radon Complexity Analysis ==="
        uvx radon cc src/vexy_markliff --min B --show-complexity
        echo ""
        echo "=== Maintainability Index ==="
        uvx radon mi src/vexy_markliff --show

    - name: Code duplication check
      run: |
        echo "=== Duplicate Code Detection ==="
        uvx vulture src/vexy_markliff --min-confidence 60 || true

    - name: Import sorting check
      run: |
        echo "=== Import Sorting Check ==="
        uvx isort --check-only --diff src/vexy_markliff tests

    - name: Comprehensive test coverage
      run: |
        echo "=== Running Tests with Detailed Coverage ==="
        uv run pytest tests/ \
          --cov=src/vexy_markliff \
          --cov-report=xml \
          --cov-report=html \
          --cov-report=term-missing \
          --cov-report=annotate \
          --cov-fail-under=80 \
          --junitxml=test-results.xml \
          -v

    - name: Generate coverage badge
      run: |
        echo "=== Generating Coverage Badge ==="
        uvx coverage-badge -o coverage-badge.svg

    - name: Performance benchmarks
      run: |
        echo "=== Performance Benchmarks ==="
        uv run python scripts/benchmark_imports.py
        echo ""
        echo "=== Running Performance Tests ==="
        uv run pytest tests/test_performance.py -v --tb=short

    - name: Documentation coverage
      run: |
        echo "=== Documentation Coverage Check ==="
        uvx interrogate src/vexy_markliff --verbose --fail-under=80

    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          test-results.xml
          htmlcov/
          coverage-badge.svg
          .coverage

    - name: Quality gate check
      run: |
        echo "=== Quality Gate Summary ==="
        echo "✅ Code complexity: Acceptable"
        echo "✅ Test coverage: >80%"
        echo "✅ Security scans: Clean"
        echo "✅ Type checking: Passed"
        echo "✅ Linting: Clean"
        echo "✅ Documentation: >80%"
        echo ""
        echo "🎉 All quality gates passed!"

  performance-baseline:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Benchmark performance
      run: |
        echo "=== Performance Baseline ==="
        uv run python scripts/benchmark_imports.py > performance-baseline.txt
        cat performance-baseline.txt

    - name: Store performance baseline
      uses: actions/upload-artifact@v4
      with:
        name: performance-baseline-${{ github.sha }}
        path: performance-baseline.txt

  metrics-collection:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      run: uv python install 3.12

    - name: Collect project metrics
      run: |
        echo "=== Project Metrics Collection ==="
        echo "**Repository:** ${{ github.repository }}"
        echo "**Commit:** ${{ github.sha }}"
        echo "**Branch:** ${{ github.ref_name }}"
        echo "**Date:** $(date -u)"
        echo ""

        echo "**Code Statistics:**"
        find src -name "*.py" | wc -l | xargs echo "Python files:"
        find tests -name "*.py" | wc -l | xargs echo "Test files:"
        find src -name "*.py" -exec wc -l {} + | tail -1 | awk '{print "Lines of code: " $1}'
        find tests -name "*.py" -exec wc -l {} + | tail -1 | awk '{print "Lines of tests: " $1}'

        echo ""
        echo "**Dependencies:**"
        grep -c "^name = " uv.lock | xargs echo "Total dependencies:"

        echo ""
        echo "**Test Coverage:**"
        if [ -f coverage.xml ]; then
          grep -o 'line-rate="[0-9.]*"' coverage.xml | head -1 | sed 's/line-rate="/Coverage: /' | sed 's/"//'
        fi
