name: Tests

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync --all-extras --dev

    - name: Run tests
      run: uv run pytest tests/ --cov=src/vexy_markliff --cov-report=term-missing -v

    - name: Check code quality
      run: |
        uvx ruff check src/vexy_markliff tests
        uvx mypy src/vexy_markliff --ignore-missing-imports
